name: Push to private repo branch
on:
  push:
    branches:
      - push_to_another_repo
  workflow_dispatch:

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Git configurations
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --local user.name test_name
      - name: Push to another repo
        uses: ad-m/github-push-action@master
        with:
          branch: 'test/pushed-from-another-repo'
          github_token: ${{ secrets.TOKEN }}
          force: true
          repository: "SalmonPorkbelly/push_target"
        env:
          GIT_COMMITTER_NAME: test_name